language: scala
scala:
   - 2.10.0
jdk:
   - oraclejdk7
before_install:
   - sudo apt-get install scala
after_script:
   - "chmod 755 scripts/bench.sh"
   - "chmod 755 scripts/run_bench.sh"
   - "scripts/bench.sh"
   - "scripts/run_bench.sh"

